# Generated by Django 2.2.7 on 2019-11-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20191111_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='result',
            name='time',
        ),
    ]
