# Generated by Django 2.2.7 on 2019-11-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20191111_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='full_json',
        ),
        migrations.AddField(
            model_name='result',
            name='clouds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='result',
            name='wind',
            field=models.FloatField(default=0),
        ),
    ]
