# Generated by Django 2.2.7 on 2019-11-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20191111_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='clouds',
        ),
        migrations.RemoveField(
            model_name='result',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='result',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='result',
            name='wind',
        ),
        migrations.AddField(
            model_name='result',
            name='full_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
