# Generated by Django 2.2.7 on 2019-11-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20191111_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
