# Generated by Django 2.2.7 on 2019-11-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_result_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
